spring:
  profiles:
    active: local   # Default Environment

# Local Environment
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Develop(DEV) Environment
---
server:
  port: 8180

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Operation Environment
---
server:
  port: 8182

spring:
  config:
    activate:
      on-profile: operation

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher